services:
  app:
    image: groupeat/groupeat-server:latest
    container_name: groupeat-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./secrets/firebase-service-account.json:/app/secrets/firebase-service-account.json:ro
    depends_on:
      - redis
      - rabbitmq
    restart: always

  redis:
    image: redis:alpine
    container_name: groupeat-redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: groupeat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-groupeat}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-groupeat}
    restart: always

  # 로그 저장소 (Loki)
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  # 시각화 대시보드 (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana     # 대시보드 설정 및 데이터 보존용 볼륨
    depends_on:
      - loki
    restart: always

  # 로그 수집기 (Grafana Alloy)
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./monitoring/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock             # 도커 엔진과 통신
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # 도커 컨테이너 로그 직접 읽기 권한
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    depends_on:
      - loki
    restart: always

  # 메트릭 수집기 (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

volumes:
  grafana-data:
